services:
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    env_file: .env
    ports: ["9621:9621"]
    depends_on:
      postgres:
        condition: service_started
      qdrant:
        condition: service_started
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./data/tiktoken:/app/data/tiktoken
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    environment:
      - TIKTOKEN_CACHE_DIR=/app/data/tiktoken
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: lightrag
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ragpass
    ports: ["5433:5432"]         # nếu host đã có Postgres, dùng 5433
    volumes:
      - pg_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:6333/readyz || curl -fsS http://localhost:6333/readyz || wget -q -O- http://localhost:6333/healthz || curl -fsS http://localhost:6333/healthz || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 40
      start_period: 5s

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-lightrag
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Timezone settings
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - TZ=Asia/Ho_Chi_Minh

      # n8n settings
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - NODE_FUNCTION_ALLOW_BUILTIN=*

      # Security settings
      - N8N_SECURE_COOKIE=false
      - N8N_PORT=5678
      - N8N_PROTOCOL=http

      # Execution settings
      - EXECUTIONS_PROCESS=main
      - N8N_METRICS=true

    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_backups:/backups
      - ./n8n/knowledge_files:/app/knowledge_files
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5678/healthz" ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pg_data:
  qdrant_data:
  n8n_data: